### PR TITLE
Update single threaded Julia versus C++ benchmarks

### PR DESCRIPTION
**Pull request by emstoudenmire**
This updates the single threaded benchmarks using ITensors.jl v0.1.35 and C++ ITensor without using tcmalloc.

### CODE REVIEW

**Comment by emstoudenmire** [comment]
The changes look as I would expect, except that the C++ CTMRG results look radically better in this PR versus the previous data. @mtfishman we should probably discuss this to be sure of what's going on, like running some "spot checks" of a few of these benchmark codes and settings.

**Comment by mtfishman** [comment]
Thanks for the update, pretty strange how much it changed. Maybe the previous runs were using the native ITensor SVD instead of LAPACK.

**Comment by mtfishman** [comment]
Would you mind also updating the plots? You should be able to just run `julia plot.jl` in the `benchmarks/julia_vs_c++/` directory.

**Comment by emstoudenmire** [comment]
Ok I successfully ran plots.jl (on my own machine, to avoid the X server issue we discussed). I updated both the 1-thread and 4-thread plots, since on the previous 4-thread PR I had not updated the plots.

**Comment by mtfishman** [comment]
Thanks. Over all the new results are what I would expect, besides the big changes in the single threaded CTMRG results. However, the results only change a lot for smaller bond dimensions, while larger bond dimension results (350-400) stay pretty similar to the previous results. Also, the new C++ CTMRG results seem to match better with the Julia version. I would expect them to be nearly the same (since it is all dense operations, both using the same BLAS/LAPACK functions and implementation, etc.), so maybe there was something wrong with the previous benchmark.

Anyway, the results seem reasonable, so we can merge this and maybe double check them later after I finish reorganizing the package.

**Pull request merged**
